Update build-deploy.yml
to correct the deployment error Release "nginx-ingress" does not exist. Installing it now.
I0521 13:03:48.697975    3353 warnings.go:110] "Warning: spec.template.spec.nodeSelector[beta.kubernetes.io/os]: deprecated since v1.14; use \"kubernetes.io/os\" instead"
Error: 1 error occurred:
	* Deployment.apps "nginx-ingress-ingress-nginx-controller" is invalid: spec.progressDeadlineSeconds: Invalid value: 0: must be greater than minReadySeconds help me fix this error